### ISSUE TITLE
Transfer ownership of repo to @regulatorystudies

### ISSUE THREAD

**Issue by mfebrizio** [regulatorystudies/Reg-Stats-Coding-Project#4]
Let's chat about this next meeting, but I wanted to open an "issue" to practice using that feature too.

You can transfer ownership to an org by going to the repository settings, going to general, and scrolling down to the bottom to the Danger Zone. Then choose transfer ownership and follow the instructions.

I've already went through this process with the regulation-digest retrieve FR clips program.

After transferring ownership, you may need to re-add the repo to your local machine if you're using Github Desktop.

**Comment by yqz5514** [comment]
Thanks for the reminder! I've just moved the repository to the organization account.

**Comment by yqz5514** [comment]
Thanks, Mark!
